extended_drawers:upgrade_frame*1.0 = {
crafting_table
minecraft:stick*1.0
minecraft:cobblestone*1.0
minecraft:stick*1.0
minecraft:cobblestone*1.0
-
minecraft:cobblestone*1.0
minecraft:stick*1.0
minecraft:cobblestone*1.0
minecraft:stick*1.0
}
extended_drawers:t1_upgrade*1.0 = {
crafting_table
minecraft:stick*1.0
minecraft:stick*1.0
minecraft:stick*1.0
extended_drawers:upgrade_frame*1.0
minecraft:barrel*1.0
extended_drawers:upgrade_frame*1.0
minecraft:stick*1.0
minecraft:stick*1.0
minecraft:stick*1.0
}
modern_industrialization:iron_rod*2.0 = {
cutting_machine
minecraft:iron_ingot*1.0
-
-
-
-
-
-
-
-
}
modern_industrialization:iron_plate*1.0 = {
compressor
minecraft:iron_ingot*1.0
-
-
-
-
-
-
-
-
}
modern_industrialization:copper_plate*1.0 = {
compressor
minecraft:copper_ingot*1.0
-
-
-
-
-
-
-
-
}
modern_industrialization:copper_wire*2.0 = {
wiremill
modern_industrialization:copper_plate*1.0
-
-
-
-
-
-
-
-
}
modern_industrialization:gold_plate*1.0 = {
compressor
minecraft:gold_ingot*1.0
-
-
-
-
-
-
-
-
}
modern_industrialization:copper_fine_wire*4.0 = {
wiremill
modern_industrialization:copper_wire*1.0
-
-
-
-
-
-
-
-
}
modern_industrialization:coal_dust*1.0 = {
macerator
minecraft:coal*1.0
-
-
-
-
-
-
-
-
}
modern_industrialization:steel_rod*2.0 = {
cutting_machine
modern_industrialization:steel_ingot*1.0
-
-
-
-
-
-
-
-
}
modern_industrialization:analog_circuit*1.0 = {
crafting_table
modern_industrialization:resistor*1.0
modern_industrialization:inductor*1.0
modern_industrialization:resistor*1.0
modern_industrialization:capacitor*1.0
modern_industrialization:analog_circuit_board*1.0
modern_industrialization:capacitor*1.0
modern_industrialization:copper_wire*1.0
modern_industrialization:copper_wire*1.0
modern_industrialization:copper_wire*1.0
}
modern_industrialization:battery_alloy_curved_plate*1.0 = {
compressor
-
-
-
-
modern_industrialization:battery_alloy_plate*1.0
-
-
-
-
}
minecraft:diamond*1.0 = {
crafting_table
techreborn:diamond_nugget*1.0
techreborn:diamond_nugget*1.0
techreborn:diamond_nugget*1.0
techreborn:diamond_nugget*1.0
techreborn:diamond_nugget*1.0
techreborn:diamond_nugget*1.0
techreborn:diamond_nugget*1.0
techreborn:diamond_nugget*1.0
techreborn:diamond_nugget*1.0
}
minecraft:iron_pickaxe*1.0 = {
crafting_table
minecraft:iron_ingot*1.0
minecraft:iron_ingot*1.0
minecraft:iron_ingot*1.0
-
minecraft:stick*1.0
-
-
minecraft:stick*1.0
-
}
minecraft:flint_and_steel*1.0 = {
crafting_table
-
-
-
minecraft:iron_ingot*1.0
-
-
-
minecraft:flint*1.0
-
}
minecraft:ender_pearl*9.0 = {
crafting_table
-
-
-
-
blockus:ender_block*1.0
-
-
-
-
}
modern_industrialization:inductor*4.0 = {
assembler
modern_industrialization:copper_wire*1.0
modern_industrialization:steel_rod*1.0
modern_industrialization:copper_wire*7.0
-
-
-
-
-
-
}
modern_industrialization:resistor*12.0 = {
assembler
modern_industrialization:copper_fine_wire*2.0
modern_industrialization:coal_dust*1.0
-
-
-
-
-
-
-
}
modern_industrialization:diode*1.0 = {
crafting_table
modern_industrialization:electrum_fine_wire*1.0
modern_industrialization:steel_plate*1.0
minecraft:glass*1.0
modern_industrialization:electrum_fine_wire*1.0
modern_industrialization:silicon_plate*1.0
minecraft:glass*1.0
modern_industrialization:electrum_fine_wire*1.0
modern_industrialization:steel_plate*1.0
minecraft:glass*1.0
}
modern_industrialization:transistor*2.0 = {
crafting_table
-
modern_industrialization:electrum_fine_wire*1.0
-
modern_industrialization:steel_plate*1.0
modern_industrialization:steel_plate*1.0
modern_industrialization:steel_plate*1.0
modern_industrialization:silicon_plate*1.0
modern_industrialization:silicon_plate*1.0
modern_industrialization:silicon_plate*1.0
}
modern_industrialization:aluminum_plate*1.0 = {
compressor
-
-
-
-
modern_industrialization:aluminum_ingot*1.0
-
-
-
-
}
modern_industrialization:battery_alloy_plate*1.0 = {
compressor
-
-
-
-
modern_industrialization:battery_alloy_ingot*1.0
-
-
-
-
}
modern_industrialization:electronic_circuit*1.0 = {
crafting_table
modern_industrialization:analog_circuit*1.0
modern_industrialization:diode*1.0
modern_industrialization:analog_circuit*1.0
modern_industrialization:transistor*1.0
modern_industrialization:electronic_circuit_board*1.0
modern_industrialization:transistor*1.0
modern_industrialization:analog_circuit*1.0
modern_industrialization:diode*1.0
modern_industrialization:analog_circuit*1.0
}
modern_industrialization:redstone_battery*1.0 = {
crafting_table
modern_industrialization:tin_cable*1.0
modern_industrialization:battery_alloy_plate*1.0
modern_industrialization:tin_cable*1.0
modern_industrialization:battery_alloy_curved_plate*1.0
minecraft:redstone*1.0
modern_industrialization:battery_alloy_curved_plate*1.0
modern_industrialization:battery_alloy_curved_plate*1.0
minecraft:redstone*1.0
modern_industrialization:battery_alloy_curved_plate*1.0
}
modern_industrialization:electronic_circuit_board*1.0 = {
crafting_table
modern_industrialization:electrum_cable*1.0
modern_industrialization:aluminum_plate*1.0
modern_industrialization:electrum_cable*1.0
modern_industrialization:aluminum_plate*1.0
modern_industrialization:analog_circuit_board*1.0
modern_industrialization:aluminum_plate*1.0
modern_industrialization:electrum_cable*1.0
modern_industrialization:redstone_battery*1.0
modern_industrialization:electrum_cable*1.0
}
modern_industrialization:electrum_fine_wire*4.0 = {
wiremill
-
-
-
-
modern_industrialization:electrum_wire*1.0
-
-
-
-
}
modern_industrialization:electrum_plate*1.0 = {
compressor
-
-
-
-
modern_industrialization:electrum_ingot*1.0
-
-
-
-
}
modern_industrialization:electrum_wire*2.0 = {
wiremill
-
-
-
-
modern_industrialization:electrum_plate*1.0
-
-
-
-
}
modern_industrialization:steel_plate*1.0 = {
compressor
modern_industrialization:steel_ingot*1.0
-
-
-
-
-
-
-
-
}
modern_industrialization:silicon_plate*1.0 = {
compressor
-
-
-
-
modern_industrialization:silicon_ingot*1.0
-
-
-
-
}
modern_industrialization:tin_wire*2.0 = {
wiremill
-
-
-
-
modern_industrialization:tin_plate*1.0
-
-
-
-
}
modern_industrialization:tin_plate*1.0 = {
compressor
-
-
-
-
modern_industrialization:tin_ingot*1.0
-
-
-
-
}
modern_industrialization:silicon_dust*1.0 = {
macerator
-
-
-
-
modern_industrialization:silicon_ingot*1.0
-
-
-
-
}
modern_industrialization:silicon_battery*1.0 = {
crafting_table
modern_industrialization:electrum_cable*1.0
modern_industrialization:battery_alloy_plate*1.0
modern_industrialization:electrum_cable*1.0
modern_industrialization:battery_alloy_curved_plate*1.0
modern_industrialization:silicon_dust*1.0
modern_industrialization:battery_alloy_curved_plate*1.0
modern_industrialization:battery_alloy_curved_plate*1.0
modern_industrialization:silicon_dust*1.0
modern_industrialization:battery_alloy_curved_plate*1.0
}
modern_industrialization:steel_ring*1.0 = {
compressor
-
-
-
-
modern_industrialization:steel_rod*1.0
-
-
-
-
}
modern_industrialization:steel_bolt*2.0 = {
cutting_machine
-
-
-
-
modern_industrialization:steel_rod*1.0
-
-
-
-
}
modern_industrialization:steel_gear*2.0 = {
assembler
modern_industrialization:steel_plate*4.0
modern_industrialization:steel_ring*1.0
-
-
-
-
-
-
-
}
modern_industrialization:steel_machine_casing*1.0 = {
crafting_table
modern_industrialization:steel_plate*1.0
modern_industrialization:steel_plate*1.0
modern_industrialization:steel_plate*1.0
modern_industrialization:steel_plate*1.0
modern_industrialization:steel_gear*1.0
modern_industrialization:steel_plate*1.0
modern_industrialization:steel_plate*1.0
modern_industrialization:steel_plate*1.0
modern_industrialization:steel_plate*1.0
}
modern_industrialization:basic_machine_hull*1.0 = {
crafting_table
-
modern_industrialization:analog_circuit*1.0
-
modern_industrialization:redstone_battery*1.0
modern_industrialization:steel_machine_casing*1.0
modern_industrialization:redstone_battery*1.0
modern_industrialization:tin_cable*1.0
modern_industrialization:tin_cable*1.0
modern_industrialization:tin_cable*1.0
}
modern_industrialization:advanced_machine_casing*1.0 = {
crafting_table
modern_industrialization:aluminum_plate*1.0
modern_industrialization:aluminum_plate*1.0
modern_industrialization:aluminum_plate*1.0
modern_industrialization:aluminum_plate*1.0
modern_industrialization:basic_machine_hull*1.0
modern_industrialization:aluminum_plate*1.0
modern_industrialization:aluminum_plate*1.0
modern_industrialization:aluminum_plate*1.0
modern_industrialization:aluminum_plate*1.0
}
modern_industrialization:advanced_machine_hull*1.0 = {
crafting_table
-
modern_industrialization:electronic_circuit*1.0
-
modern_industrialization:silicon_battery*1.0
modern_industrialization:advanced_machine_casing*1.0
modern_industrialization:silicon_battery*1.0
modern_industrialization:electrum_cable*1.0
modern_industrialization:electrum_cable*1.0
modern_industrialization:electrum_cable*1.0
}
modern_industrialization:steel_rod_magnetic*1.0 = {
polarizer
-
-
-
-
modern_industrialization:steel_rod*1.0
-
-
-
-
}
modern_industrialization:motor*1.0 = {
crafting_table
modern_industrialization:tin_cable*1.0
modern_industrialization:copper_wire*1.0
modern_industrialization:steel_rod*1.0
modern_industrialization:copper_wire*1.0
modern_industrialization:steel_rod_magnetic*1.0
modern_industrialization:copper_wire*1.0
modern_industrialization:steel_rod*1.0
modern_industrialization:copper_wire*1.0
modern_industrialization:tin_cable*1.0
}
modern_industrialization:aluminum_rod*2.0 = {
cutting_machine
-
-
-
-
modern_industrialization:aluminum_ingot*1.0
-
-
-
-
}
modern_industrialization:large_motor*1.0 = {
crafting_table
modern_industrialization:motor*1.0
modern_industrialization:motor*1.0
modern_industrialization:motor*1.0
modern_industrialization:electronic_circuit*1.0
modern_industrialization:aluminum_rod*1.0
modern_industrialization:aluminum_rod*1.0
modern_industrialization:motor*1.0
modern_industrialization:motor*1.0
modern_industrialization:motor*1.0
}
modern_industrialization:tin_rod*2.0 = {
cutting_machine
-
-
-
-
modern_industrialization:tin_ingot*1.0
-
-
-
-
}
modern_industrialization:tin_curved_plate*1.0 = {
compressor
-
-
-
-
modern_industrialization:tin_plate*1.0
-
-
-
-
}
modern_industrialization:tin_blade*4.0 = {
crafting_table
-
modern_industrialization:tin_curved_plate*1.0
-
-
modern_industrialization:tin_curved_plate*1.0
-
-
modern_industrialization:tin_rod*1.0
-
}
modern_industrialization:tin_ring*1.0 = {
compressor
-
-
-
-
modern_industrialization:tin_rod*1.0
-
-
-
-
}
modern_industrialization:tin_rotor*1.0 = {
assembler
modern_industrialization:tin_blade*4.0
modern_industrialization:tin_ring*1.0
-
-
-
-
-
-
-
}
minecraft:glass_pane*16.0 = {
crafting_table
-
-
-
minecraft:glass*1.0
minecraft:glass*1.0
minecraft:glass*1.0
minecraft:glass*1.0
minecraft:glass*1.0
minecraft:glass*1.0
}
modern_industrialization:copper_rod*2.0 = {
cutting_machine
-
-
-
-
minecraft:copper_ingot*1.0
-
-
-
-
}
modern_industrialization:copper_curved_plate*1.0 = {
compressor
-
-
-
-
modern_industrialization:copper_plate*1.0
-
-
-
-
}
modern_industrialization:copper_blade*4.0 = {
crafting_table
-
modern_industrialization:copper_curved_plate*1.0
-
-
modern_industrialization:copper_curved_plate*1.0
-
-
modern_industrialization:copper_rod*1.0
-
}
modern_industrialization:copper_ring*1.0 = {
compressor
-
-
-
-
modern_industrialization:copper_rod*1.0
-
-
-
-
}
modern_industrialization:copper_rotor*1.0 = {
assembler
modern_industrialization:copper_blade*4.0
modern_industrialization:copper_ring*1.0
-
-
-
-
-
-
-
}
modern_industrialization:bronze_plate*1.0 = {
compressor
-
-
-
-
modern_industrialization:bronze_ingot*1.0
-
-
-
-
}
modern_industrialization:bronze_curved_plate*1.0 = {
compressor
-
-
-
-
modern_industrialization:bronze_plate*1.0
-
-
-
-
}
modern_industrialization:pump*1.0 = {
assembler
modern_industrialization:fluid_pipe*3.0
modern_industrialization:tin_rotor*3.0
modern_industrialization:motor*1.0
-
-
-
-
-
-
}
modern_industrialization:aluminum_ring*1.0 = {
compressor
-
-
-
-
modern_industrialization:aluminum_rod*1.0
-
-
-
-
}
modern_industrialization:aluminum_curved_plate*1.0 = {
compressor
-
-
-
-
modern_industrialization:aluminum_plate*1.0
-
-
-
-
}
modern_industrialization:aluminum_blade*4.0 = {
crafting_table
-
modern_industrialization:aluminum_curved_plate*1.0
-
-
modern_industrialization:aluminum_curved_plate*1.0
-
-
modern_industrialization:aluminum_rod*1.0
-
}
modern_industrialization:aluminum_rotor*1.0 = {
assembler
modern_industrialization:aluminum_blade*4.0
modern_industrialization:aluminum_ring*1.0
-
-
-
-
-
-
-
}
modern_industrialization:large_pump*1.0 = {
crafting_table
modern_industrialization:pump*1.0
modern_industrialization:pump*1.0
modern_industrialization:pump*1.0
modern_industrialization:aluminum_rotor*1.0
modern_industrialization:large_motor*1.0
modern_industrialization:aluminum_rotor*1.0
modern_industrialization:electronic_circuit*1.0
modern_industrialization:aluminum_rotor*1.0
modern_industrialization:electronic_circuit*1.0
}
modern_industrialization:centrifuge*1.0 = {
crafting_table
modern_industrialization:large_motor*1.0
modern_industrialization:large_pump*1.0
modern_industrialization:large_motor*1.0
modern_industrialization:electrum_cable*1.0
modern_industrialization:basic_machine_hull*1.0
modern_industrialization:electrum_cable*1.0
modern_industrialization:large_motor*1.0
modern_industrialization:electronic_circuit*1.0
modern_industrialization:large_motor*1.0
}
modern_industrialization:electrum_cable*3.0 = {
assembler for cabels
modern_industrialization:electrum_wire*3.0
-
-
-
-
-
-
-
-
}
modern_industrialization:tin_cable*3.0 = {
assembler for cabels
modern_industrialization:tin_wire*3.0
-
-
-
-
-
-
-
-
}
modern_industrialization:item_pipe*16.0 = {
crafting_table
modern_industrialization:bronze_curved_plate*1.0
modern_industrialization:bronze_curved_plate*1.0
modern_industrialization:bronze_curved_plate*1.0
modern_industrialization:steel_gear*1.0
-
modern_industrialization:steel_gear*1.0
modern_industrialization:bronze_curved_plate*1.0
modern_industrialization:bronze_curved_plate*1.0
modern_industrialization:bronze_curved_plate*1.0
}
modern_industrialization:bronze_ingot*4.0 = {
alloy_smelter
minecraft:copper_ingot*3.0
modern_industrialization:tin_ingot*1.0
-
-
-
-
-
-
-
}
modern_industrialization:fluid_pipe*16.0 = {
crafting_table
modern_industrialization:bronze_curved_plate*1.0
modern_industrialization:bronze_curved_plate*1.0
modern_industrialization:bronze_curved_plate*1.0
modern_industrialization:copper_rotor*1.0
minecraft:glass_pane*1.0
modern_industrialization:copper_rotor*1.0
modern_industrialization:bronze_curved_plate*1.0
modern_industrialization:bronze_curved_plate*1.0
modern_industrialization:bronze_curved_plate*1.0
}
modern_industrialization:iron_ring*1.0 = {
compressor
modern_industrialization:iron_rod*1.0
-
-
-
-
-
-
-
-
}
modern_industrialization:iron_gear*2.0 = {
assembler
modern_industrialization:iron_plate*4.0
modern_industrialization:iron_ring*1.0
-
-
-
-
-
-
-
}
modern_industrialization:copper_gear*2.0 = {
assembler
modern_industrialization:copper_plate*4.0
modern_industrialization:copper_ring*1.0
-
-
-
-
-
-
-
}
modern_industrialization:copper_drill_head*1.0 = {
assembler
modern_industrialization:copper_plate*1.0
modern_industrialization:copper_curved_plate*2.0
modern_industrialization:copper_rod*1.0
modern_industrialization:copper_gear*2.0
-
-
-
-
-
}
modern_industrialization:copper_drill*4.0 = {
crafting_table
-
-
modern_industrialization:copper_drill_head*1.0
modern_industrialization:iron_gear*1.0
modern_industrialization:item_pipe*1.0
-
modern_industrialization:fluid_pipe*1.0
modern_industrialization:iron_gear*1.0
-
}
modern_industrialization:aluminum_gear*2.0 = {
assembler
modern_industrialization:aluminum_plate*4.0
modern_industrialization:aluminum_ring*1.0
-
-
-
-
-
-
-
}
modern_industrialization:aluminum_drill_head*1.0 = {
assembler
modern_industrialization:aluminum_plate*1.0
modern_industrialization:aluminum_curved_plate*2.0
modern_industrialization:aluminum_rod*1.0
modern_industrialization:aluminum_gear*2.0
-
-
-
-
-
}
modern_industrialization:aluminum_drill*4.0 = {
crafting_table
modern_industrialization:iron_gear*1.0
modern_industrialization:fluid_pipe*1.0
modern_industrialization:aluminum_drill_head*1.0
modern_industrialization:pump*1.0
modern_industrialization:electronic_circuit*1.0
modern_industrialization:fluid_pipe*1.0
modern_industrialization:electrum_cable*1.0
modern_industrialization:pump*1.0
modern_industrialization:iron_gear*1.0
}
modern_industrialization:bronze_rod*2.0 = {
cutting_machine
modern_industrialization:bronze_ingot*1.0
-
-
-
-
-
-
-
-
}
modern_industrialization:bronze_ring*1.0 = {
compressor
modern_industrialization:bronze_rod*1.0
-
-
-
-
-
-
-
-
}
modern_industrialization:bronze_gear*2.0 = {
assembler
modern_industrialization:bronze_plate*4.0
modern_industrialization:bronze_ring*1.0
-
-
-
-
-
-
-
}
modern_industrialization:bronze_drill_head*1.0 = {
assembler
modern_industrialization:bronze_plate*1.0
modern_industrialization:bronze_curved_plate*2.0
modern_industrialization:bronze_rod*1.0
modern_industrialization:bronze_gear*2.0
-
-
-
-
-
}
modern_industrialization:bronze_drill*4.0 = {
crafting_table
-
-
modern_industrialization:bronze_drill_head*1.0
modern_industrialization:iron_gear*1.0
modern_industrialization:item_pipe*1.0
-
modern_industrialization:fluid_pipe*1.0
modern_industrialization:iron_gear*1.0
-
}
modern_industrialization:gold_rod*2.0 = {
cutting_machine
minecraft:gold_ingot*1.0
-
-
-
-
-
-
-
-
}
modern_industrialization:gold_ring*1.0 = {
compressor
modern_industrialization:gold_rod*1.0
-
-
-
-
-
-
-
-
}
modern_industrialization:gold_gear*2.0 = {
assembler
modern_industrialization:gold_plate*4.0
modern_industrialization:gold_ring*1.0
-
-
-
-
-
-
-
}
modern_industrialization:gold_curved_plate*1.0 = {
compressor
modern_industrialization:gold_plate*1.0
-
-
-
-
-
-
-
-
}
modern_industrialization:gold_drill_head*1.0 = {
assembler
modern_industrialization:gold_plate*1.0
modern_industrialization:gold_curved_plate*2.0
modern_industrialization:gold_rod*1.0
modern_industrialization:gold_gear*2.0
-
-
-
-
-
}
modern_industrialization:gold_drill*4.0 = {
crafting_table
modern_industrialization:iron_gear*1.0
modern_industrialization:item_pipe*1.0
modern_industrialization:gold_drill_head*1.0
modern_industrialization:motor*1.0
modern_industrialization:analog_circuit*1.0
modern_industrialization:item_pipe*1.0
modern_industrialization:tin_cable*1.0
modern_industrialization:motor*1.0
modern_industrialization:iron_gear*1.0
}
create:electron_tube*1.0 = {
crafting_table
create:polished_rose_quartz*1.0
-
-
modern_industrialization:iron_plate*1.0
-
-
-
-
-
}
modern_industrialization:zinc_plate*1.0 = {
compressor
techreborn:zinc_ingot*1.0
-
-
-
-
-
-
-
-
}
modern_industrialization:zinc_curved_plate*1.0 = {
compressor
modern_industrialization:zinc_plate*1.0
-
-
-
-
-
-
-
-
}
modern_industrialization:zinc_rod*2.0 = {
cutting_machine
techreborn:zinc_ingot*1.0
-
-
-
-
-
-
-
-
}
modern_industrialization:zinc_ring*1.0 = {
compressor
modern_industrialization:zinc_rod*1.0
-
-
-
-
-
-
-
-
}
modern_industrialization:zinc_gear*2.0 = {
assembler
modern_industrialization:zinc_plate*4.0
modern_industrialization:zinc_ring*1.0
-
-
-
-
-
-
-
}
modern_industrialization:zinc_drill_head*1.0 = {
assembler
modern_industrialization:zinc_plate*1.0
modern_industrialization:zinc_curved_plate*2.0
modern_industrialization:zinc_rod*1.0
modern_industrialization:zinc_gear*2.0
-
-
-
-
-
}
modern_industrialization:zinc_drill*4.0 = {
crafting_table
-
-
modern_industrialization:zinc_drill_head*1.0
modern_industrialization:iron_gear*1.0
create:electron_tube*1.0
-
modern_industrialization:bronze_plate*1.0
modern_industrialization:iron_gear*1.0
-
}
modern_industrialization:steel_curved_plate*1.0 = {
compressor
modern_industrialization:steel_plate*1.0
-
-
-
-
-
-
-
-
}
modern_industrialization:steel_drill_head*1.0 = {
assembler
modern_industrialization:steel_plate*1.0
modern_industrialization:steel_curved_plate*2.0
modern_industrialization:steel_rod*1.0
modern_industrialization:steel_gear*2.0
-
-
-
-
-
}
modern_industrialization:steel_drill*4.0 = {
crafting_table
modern_industrialization:iron_gear*1.0
modern_industrialization:item_pipe*1.0
modern_industrialization:steel_drill_head*1.0
modern_industrialization:motor*1.0
modern_industrialization:analog_circuit*1.0
modern_industrialization:item_pipe*1.0
modern_industrialization:tin_cable*1.0
modern_industrialization:motor*1.0
modern_industrialization:iron_gear*1.0
}
extended_drawers:t2_upgrade*1.0 = {
crafting_table
modern_industrialization:iron_rod*1.0
modern_industrialization:iron_rod*1.0
modern_industrialization:iron_rod*1.0
extended_drawers:t1_upgrade*1.0
minecraft:iron_ingot*1.0
extended_drawers:t1_upgrade*1.0
modern_industrialization:iron_rod*1.0
modern_industrialization:iron_rod*1.0
modern_industrialization:iron_rod*1.0
}
extended_drawers:t3_upgrade*1.0 = {
crafting_table
modern_industrialization:bronze_rod*1.0
modern_industrialization:bronze_rod*1.0
modern_industrialization:bronze_rod*1.0
extended_drawers:t2_upgrade*1.0
minecraft:gold_ingot*1.0
extended_drawers:t2_upgrade*1.0
modern_industrialization:bronze_rod*1.0
modern_industrialization:bronze_rod*1.0
modern_industrialization:bronze_rod*1.0
}
extended_drawers:t4_upgrade*1.0 = {
crafting_table
modern_industrialization:steel_rod*1.0
modern_industrialization:steel_rod*1.0
modern_industrialization:steel_rod*1.0
extended_drawers:t3_upgrade*1.0
minecraft:diamond*1.0
extended_drawers:t3_upgrade*1.0
modern_industrialization:steel_rod*1.0
modern_industrialization:steel_rod*1.0
modern_industrialization:steel_rod*1.0
}
modern_industrialization:battery_alloy_ingot*2.0 = {
alloy_smelter
modern_industrialization:lead_ingot*1.0
modern_industrialization:antimony_ingot*1.0
-
-
-
-
-
-
-
}
modern_industrialization:electrum_ingot*4.0 = {
alloy_smelter
minecraft:gold_ingot*2.0
modern_industrialization:silver_ingot*2.0
-
-
-
-
-
-
-
}
minecraft:glass*1.0 = {
furnace
minecraft:sand*1.0
-
-
-
-
-
-
-
-
}
modern_industrialization:bronze_tank*1.0 = {
crafting_table
modern_industrialization:bronze_plate*1.0
modern_industrialization:bronze_plate*1.0
modern_industrialization:bronze_plate*1.0
modern_industrialization:bronze_plate*1.0
minecraft:glass*1.0
modern_industrialization:bronze_plate*1.0
modern_industrialization:bronze_plate*1.0
modern_industrialization:bronze_plate*1.0
modern_industrialization:bronze_plate*1.0
}
modern_industrialization:steel_tank*1.0 = {
crafting_table
modern_industrialization:steel_plate*1.0
modern_industrialization:steel_plate*1.0
modern_industrialization:steel_plate*1.0
modern_industrialization:steel_plate*1.0
minecraft:glass*1.0
modern_industrialization:steel_plate*1.0
modern_industrialization:steel_plate*1.0
modern_industrialization:steel_plate*1.0
modern_industrialization:steel_plate*1.0
}
modern_industrialization:aluminum_tank*1.0 = {
crafting_table
modern_industrialization:aluminum_plate*1.0
modern_industrialization:aluminum_plate*1.0
modern_industrialization:aluminum_plate*1.0
modern_industrialization:aluminum_plate*1.0
minecraft:glass*1.0
modern_industrialization:aluminum_plate*1.0
modern_industrialization:aluminum_plate*1.0
modern_industrialization:aluminum_plate*1.0
modern_industrialization:aluminum_plate*1.0
}
